# Generated by Django 6.1.1 on 2026-09-25 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='author',
            name='author_name_52ee50_idx',
        ),
        migrations.RemoveIndex(
            model_name='book',
            name='book_title_b1b2be_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_name_c1301d_idx',
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='作者姓名'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, unique=True, verbose_name='图书名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='标签名称'),
        ),
    ]
