# Generated by Django 6.1.1 on 2026-09-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_author_author_name_52ee50_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='标签描述'),
        ),
        migrations.AddIndex(
            model_name='author',
            index=models.Index(fields=['name', 'age'], name='author_name_52ee50_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['title', 'author_name'], name='book_title_b1b2be_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['name'], name='tag_name_c1301d_idx'),
        ),
    ]
